include $(TOPDIR)/rules.mk

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Quanljh <quanljh@gmail.com>

LUCI_TITLE:=LuCI app for dae
LUCI_DEPENDS:=+dae +dae-geoip +dae-geosite

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
